name: Metro ETL Run on Runner

on:
  push:
    branches: [ main ]

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and Push to Registry
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/metro-repo/scraper:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Now we pull it back to the runner and run the scripts
      - name: Run Station Scraper
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/metro-repo/scraper:latest"
          docker run $IMAGE_NAME python station_etl.py

      - name: Run Route Scraper
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/metro-repo/scraper:latest"
          docker run $IMAGE_NAME python route_etl.py